### ISSUE TITLE
multiple pair

### ISSUE THREAD

**Issue by onthetunnel** [jakesee/binance-trader#8]
hello,  can i know this project can do auto track all BTC pair on binance and auto order multiple uptrend(using TA strategy or DCA)coin and auto sell it when hit profit % or stoploss? and can add blacklist/whitelist for coin .. if this project can do these work 24/7 without any problem , i will donate you some BTC for this project , Thanks You!

**Comment by jakesee** [comment]
Hi @onthetunnel yes, this application can track multiple BTC pairs and buy based on TA, sell based on % and DCA, but it does not have a GUI and I tweak settings directly in config file. You will need programming knowledge to understand the code to gain confidence.

**Comment by onthetunnel** [comment]
Thabks For your reply ! can you teach me how to edit the config file for tracking multiple pair using BB strategy and sell the coin hit % ,  Thanks You !
